/**
 * Executable bandit strategies.
 *
 * A bandit strategy is now a REAL JavaScript function the AI writes for the
 * student — the body of `pull(state)` that returns which machine to play.
 * It gets everything a player writing results down would have, including a
 * dictionary of every payoff from every machine, so it can do genuinely
 * arbitrary logic ("fancy stuff") rather than fit a fixed rule format.
 *
 * SAFETY: the code is generated by a constrained LLM and shown to the
 * student, but it still runs server-side over the shared world set, so it
 * is locked down:
 *   • a static denylist rejects loops (for/while/do), function-declaration
 *     recursion, and every host escape (require/process/globalThis/this/
 *     constructor/eval/Function/Promise/timers/…) BEFORE it is compiled;
 *   • it runs in strict mode with ONLY `state` and a curated `lib` in scope
 *     (`this` is undefined, so the classic global-reach tricks are dead);
 *   • randomness comes from a SEEDED `state.rng()` (Math.random is blocked)
 *     so 10,000-world runs stay deterministic and fair for everyone;
 *   • the return value is validated to a real machine index every pull.
 * List logic is expressed with array methods (.map/.filter/.reduce/…) over
 * the finite machine/payoff arrays, which cannot loop forever — so blocking
 * for/while costs nothing and removes the infinite-loop foot-gun.
 */

import { makeWorld, payoffAt, oracle, round2 } from "./bandit.js";
import { BANDIT } from "./rules.js";
import { rngFrom } from "./rng.js";

const M = BANDIT.machines;
const NAMES = BANDIT.names.slice(0, M);
const NAME_INDEX = Object.fromEntries(NAMES.map((n, i) => [n, i]));

// Tokens that must never appear in a strategy. Word-boundary matched so
// "format" doesn't trip "for", but "for(" / "for " / "while" do.
const DENY = [
  "\\bfor\\b", "\\bwhile\\b", "\\bdo\\b", "\\bfunction\\b",
  "\\bthis\\b", "\\barguments\\b", "\\bconstructor\\b", "__proto__", "\\bprototype\\b",
  "\\bimport\\b", "\\brequire\\b", "\\bprocess\\b", "\\bglobal\\b", "\\bglobalThis\\b",
  "\\beval\\b", "\\bFunction\\b", "\\bReflect\\b", "\\bProxy\\b", "\\bSymbol\\b",
  "\\bfetch\\b", "\\bXMLHttpRequest\\b", "\\bWebAssembly\\b", "\\bAtomics\\b",
  "\\bSharedArrayBuffer\\b", "\\bBuffer\\b", "\\bmodule\\b", "\\bexports\\b",
  "\\basync\\b", "\\bawait\\b", "\\byield\\b",
  "\\bsetTimeout\\b", "\\bsetInterval\\b", "\\bsetImmediate\\b", "\\bqueueMicrotask\\b",
  "\\bPromise\\b", "\\.\\s*random", "\\.\\s*constructor",
];
const DENY_RE = new RegExp(DENY.join("|"), "i");

export function validateBanditCode(src) {
  if (typeof src !== "string" || !src.trim()) return { ok: false, error: "empty code" };
  if (src.length > 4000) return { ok: false, error: "code is too long" };
  if (/[`]/.test(src)) return { ok: false, error: "template literals (backticks) aren't allowed" };
  const m = src.match(DENY_RE);
  if (m) {
    return {
      ok: false,
      error: `"${m[0].trim()}" isn't allowed — use array methods (.filter/.map/.reduce/.sort) over state.machines instead of loops, state.rng() instead of Math.random, and only the state object.`,
    };
  }
  return { ok: true };
}

/** A small, safe helper library exposed to strategy code as `lib`. */
const LIB = Object.freeze({
  max: Math.max, min: Math.min, abs: Math.abs, floor: Math.floor,
  ceil: Math.ceil, round: Math.round, sqrt: Math.sqrt, log: Math.log,
  pow: Math.pow, exp: Math.exp, sign: Math.sign,
  clamp: (x, lo, hi) => Math.max(lo, Math.min(hi, x)),
});

/**
 * Compile the code into a callable (state) => machineIndex. Throws on a
 * syntax error. Assumes validateBanditCode already passed.
 */
export function compileBanditCode(src) {
  // eslint-disable-next-line no-new-func
  const raw = new Function("state", "lib", `"use strict";\n${src}`);
  return (state) => {
    const out = raw(state, LIB);
    let idx = typeof out === "string" ? NAME_INDEX[out.trim().toUpperCase()] : out;
    idx = Math.trunc(Number(idx));
    if (!Number.isInteger(idx) || idx < 0 || idx >= M) return null; // caller handles
    return idx;
  };
}

/** Build the state object handed to the strategy for one decision. */
function makeState(rec, ctx) {
  const machines = NAMES.map((name, i) => {
    const p = rec[i];
    const plays = p.length;
    const sum = p.reduce((a, b) => a + b, 0);
    return {
      name,
      index: i,
      plays,
      payoffs: p, // the full record, in order (live reference — cheap)
      total: round2(sum),
      mean: plays ? round2(sum / plays) : 0,
      last: plays ? p[plays - 1] : null,
      best: plays ? Math.max(...p) : null,
      worst: plays ? Math.min(...p) : null,
      wins: p.reduce((n, x) => n + (x > 0 ? 1 : 0), 0),
    };
  });
  // The dictionary the student asked for: machine name → list of every payoff.
  const history = {};
  for (const mc of machines) history[mc.name] = mc.payoffs;
  return {
    pull: ctx.pull,
    pullsLeft: BANDIT.spins - ctx.pull,
    total: round2(ctx.total),
    lastMachine: ctx.lastMachine == null ? null : NAMES[ctx.lastMachine],
    lastPayoff: ctx.lastPayoff,
    machines,
    history,
    rng: ctx.rng,
  };
}

/** Run one compiled strategy over one world. */
export function simulateCode(fn, worldSeed, { withHistory = false } = {}) {
  const world = makeWorld(worldSeed);
  const rand = rngFrom(worldSeed + "|strat");
  const rec = Array.from({ length: M }, () => []);
  const ctx = { pull: 0, total: 0, lastMachine: null, lastPayoff: null, rng: rand };
  const hist = withHistory ? [] : null;
  let errored = false;

  for (let t = 0; t < BANDIT.spins; t++) {
    let machine;
    try {
      machine = fn(makeState(rec, ctx));
    } catch {
      machine = null;
    }
    if (machine == null) {
      errored = true;
      // Fall back to the least-played machine so a stray bad turn doesn't
      // tank the whole run; a strategy that ALWAYS faults is caught at
      // compile time by the smoke test.
      machine = leastPlayed(rec);
    }
    const pay = payoffAt(worldSeed, world, t, machine);
    rec[machine].push(round2(pay));
    ctx.total += pay;
    ctx.lastMachine = machine;
    ctx.lastPayoff = round2(pay);
    ctx.pull = t + 1;
    if (hist) hist.push({ t, machine, pay: round2(pay) });
  }
  return { total: round2(ctx.total), world, history: hist, errored };
}

function leastPlayed(rec) {
  let best = 0;
  for (let i = 1; i < M; i++) if (rec[i].length < rec[best].length) best = i;
  return best;
}

/** Compile + smoke test. Returns { ok, run } or { ok:false, error }. */
export function prepareBanditCode(src) {
  const v = validateBanditCode(src);
  if (!v.ok) return v;
  let fn;
  try {
    fn = compileBanditCode(src);
  } catch (e) {
    return { ok: false, error: `syntax error: ${e.message}` };
  }
  // Smoke test: it must return a valid machine on both an empty board and a
  // mid-game board, without throwing.
  try {
    const empty = makeState(Array.from({ length: M }, () => []), { pull: 0, total: 0, lastMachine: null, lastPayoff: null, rng: rngFrom("smoke") });
    const mid = makeState(Array.from({ length: M }, (_, i) => [i - 3, 2 * i - 5]), { pull: 16, total: 4, lastMachine: 0, lastPayoff: -1, rng: rngFrom("smoke2") });
    const a = fn(empty), b = fn(mid);
    if (a == null || b == null) return { ok: false, error: "the code didn't return a valid machine (return a machine index 0–7 or a name)" };
  } catch (e) {
    return { ok: false, error: `the code crashed when run: ${e.message}` };
  }
  return { ok: true, run: fn };
}

/** Aggregate a compiled strategy over the shared world set. */
export function runManyCode(fn, baseSeed, n = BANDIT.simulations) {
  let sum = 0, sumSq = 0, oracleSum = 0, best = -Infinity, worst = Infinity;
  for (let j = 0; j < n; j++) {
    const worldSeed = `${baseSeed}|w${j}`;
    const { total, world } = simulateCode(fn, worldSeed);
    sum += total;
    sumSq += total * total;
    oracleSum += oracle(world);
    if (total > best) best = total;
    if (total < worst) worst = total;
  }
  const avg = sum / n;
  const sd = Math.sqrt(Math.max(0, sumSq / n - avg * avg));
  return {
    n,
    avg: round2(avg),
    sd: round2(sd),
    best: round2(best),
    worst: round2(worst),
    oraclePct: round2((100 * sum) / oracleSum),
    avgOracle: round2(oracleSum / n),
  };
}
